#!/bin/bash
# This script will get the backtraces all the coredumps in /tmp/coredumps
# and print them to stdout.
# It will also print the name of the coredump file.
# It will also print the name of the binary that crashed.
#

# Get the list of coredumps
COREDUMP_DIR=/tmp/pytest-of-$(whoami)/pytest-current/
echo "Coredump dir: $COREDUMP_DIR"
COREDUMPS=$(find $COREDUMP_DIR -name "*core*")
for core in $COREDUMPS
do
    # # Get the name of the binary that crashed
    binary=$(gdb -c $core -batch -ex quit | grep "Core was generated by" | sed -e "s/\`//g" | awk '{print $5}' | sed -e "s/\.\///g")
    echo "Core file, Binary: $core, $binary"
    # append the core path to the binary name
    binary=$(echo $core | sed -e "s/core.*//g")$binary
    echo "Binary: $binary"
    gdb $binary $core -batch -ex "thread apply all backtrace full" -ex "quit"
done
