#! /usr/bin/env python
# encoding: utf-8

bld.stlib(
    features='cxx',
    source=bld.path.ant_glob('**/*.cpp'),
    target='tunnel',
    use=['boost_includes', 'boost_system'],
    export_includes=['..']
)
