#! /usr/bin/env python
# encoding: utf-8

bld.program(
    features='cxx',
    source=['example.cpp'],
    target='example',
    use=['tunnel'])

bld.program(
    features='cxx',
    source=['udp_tunnel.cpp'],
    target='udp_tunnel',
    use=['tunnel', 'links'])
