name: CMake
on: [push, pull_request]
jobs:
  # Build performed on runner using make specs
  cxx_mkspec:
    strategy:
      fail-fast: false
      matrix:
        config:
          - cxx_mkspec: cxx_clang70_x64
            name: Clang 7.0 64-Bit
          - cxx_mkspec: cxx_gxx83_x64
            name: GCC 8.3 64-Bit
    runs-on: [self-hosted, "${{ matrix.config.cxx_mkspec }}"]
    name: ${{ matrix.config.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        env:
          GIT_SSH_COMMAND: "ssh -i /home/buildbot/.ssh/id_ed25519 -o IdentitiesOnly=yes"
        run: python3 waf configure --git_protocol=git@ --cxx_mkspec=${{ matrix.config.cxx_mkspec }}
      - name: Build
        run: |
          echo "::add-matcher::.github/gcc-problem-matcher.json"
          python3 waf
      - name: Test
        run: python3 waf --run_tests
